# 클라이언트(Kibana, Logstash 등)가 접근하기 위한 서비스
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
# Elasticsearch 노드 간의 통신(Discovery)을 위한 Headless 서비스
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  labels:
    app: elasticsearch
spec:
  clusterIP: None # Headless 서비스로 설정
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300
      targetPort: 9300
