apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch-headless # Headless 서비스와 연결
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
        resources: 
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
          - name: "discovery.seed_hosts"
            value: "es-cluster-0.elasticsearch-headless,es-cluster-1.elasticsearch-headless,es-cluster-2.elasticsearch-headless"
          - name: "cluster.initial_master_nodes"
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: "ES_JAVA_OPTS"
            value: "-Xms1g -Xmx1g" # 메모리 설정 (requests/limits와 맞추는 것이 좋음)
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates: # 각 Pod에 대한 영구 스토리지(PVC)를 동적으로 생성
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi # 스토리지 용량 설정
